# Generated by Django 5.2.1 on 2026-03-28 00:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessingJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('segmentation_pending', 'Segmentation Pending'), ('report_requested', 'Report Requested'), ('draft_ready', 'Draft Ready'), ('dentist_reviewed', 'Dentist Reviewed'), ('finalized', 'Finalized'), ('failed', 'Failed')], default='queued', max_length=30)),
                ('is_fallback_mode', models.BooleanField(default=True)),
                ('annotated_image_url', models.URLField(blank=True)),
                ('draft_report', models.TextField(blank=True)),
                ('dentist_notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ct_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='dentapp.ctscan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='dentapp_aip_status_0a4148_idx'), models.Index(fields=['ct_scan', '-created_at'], name='dentapp_aip_ct_scan_6dea16_idx')],
            },
        ),
    ]
