# Generated by Django 5.2.1 on 2026-04-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0003_fix_legacy_profile_fk_columns'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='appointment_date_not_in_past',
        ),
    ]
