# Generated by Django 5.2.1 on 2026-04-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0005_user_email_unique'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dentistpatientlink',
            name='dentapp_den_connect_f1e8ac_idx',
        ),
    ]
