# Generated by Django 5.2.1 on 2026-04-29 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0011_rebuild_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctscan',
            name='file',
            field=models.FileField(upload_to='ct_scans/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dcm', 'nii', 'nrrd', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
