# Generated by Django 5.2.1 on 2026-05-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0015_dental_report_annotated_scan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dentalreport',
            new_name='dentapp_den_ct_scan_ab4130_idx',
            old_name='dentapp_den_ct_scan_idx',
        ),
        migrations.RenameIndex(
            model_name='dentalreport',
            new_name='dentapp_den_status_5e02d8_idx',
            old_name='dentapp_den_status_idx',
        ),
    ]
