# Generated by Django 5.2.1 on 2026-05-05 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dentapp", "0015_backfill_conversations"),
        (
            "dentapp",
            "0016_rename_dentapp_den_ct_scan_idx_dentapp_den_ct_scan_ab4130_idx_and_more",
        ),
    ]

    operations = []
