# Generated by Django 5.2.1 on 2026-05-06 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dentapp", "0017_merge_20260505_2100"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="counter_proposal_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="appointment",
            name="last_proposed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposed_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="proposal_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_dentist", "Pending Dentist"),
                    ("pending_patient", "Pending Patient"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("no_show", "No Show"),
                ],
                default="pending_dentist",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DentistAvailabilityOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_overrides",
                        to="dentapp.dentist",
                    ),
                ),
            ],
            options={
                "ordering": ["dentist", "date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["dentist", "date"],
                        name="dentapp_den_dentist_6c4856_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DentistSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "dentist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="dentapp.dentist",
                    ),
                ),
            ],
            options={
                "ordering": ["dentist", "weekday", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["dentist", "weekday"],
                        name="dentapp_den_dentist_454949_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("appointment_requested", "Appointment Requested"),
                            (
                                "appointment_counter_proposed",
                                "Appointment Counter-Proposed",
                            ),
                            ("appointment_accepted", "Appointment Accepted"),
                            ("appointment_declined", "Appointment Declined"),
                            ("appointment_cancelled", "Appointment Cancelled"),
                            ("appointment_modified", "Appointment Modified"),
                        ],
                        max_length=40,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="dentapp.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="dentapp_not_recipie_4fbc20_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="dentapp_not_recipie_fadf29_idx",
                    ),
                ],
            },
        ),
    ]
