# Generated by Django 5.2.1 on 2026-05-20 22:05

from django.db import migrations, models


def verify_existing_dentists(apps, schema_editor):
    Dentist = apps.get_model("dentapp", "Dentist")
    Dentist.objects.filter(deleted_at__isnull=True).update(is_verified=True)


class Migration(migrations.Migration):
    dependencies = [
        ("dentapp", "0020_seed_default_dentist_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="dentist",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(verify_existing_dentists, migrations.RunPython.noop),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
