"""
Tests for the unified dental analysis workflow.

Run with:  python manage.py test dentapp.tests.test_analysis_workflow
"""
import io
from unittest.mock import patch

from django.contrib.auth import get_user_model
from django.test import TestCase
from django.utils import timezone
from PIL import Image
from rest_framework.test import APIClient

from dentapp.models import AnnotatedScan, CTScan, DentalReport, Dentist, DentistPatientLink, Patient
from dentapp.tasks.analysis import analyze_ct_scan_and_generate_report as _analysis_task

User = get_user_model()


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _make_png_bytes() -> bytes:
    buf = io.BytesIO()
    Image.new('RGB', (64, 64), color=(200, 200, 200)).save(buf, format='PNG')
    return buf.getvalue()


def _create_dentist(username='dr_test'):
    user = User.objects.create_user(
        username=username, email=f'{username}@test.com',
        password='testpass123', full_name='Dr Test'
    )
    return Dentist.objects.create(dentist=user, location='Tunis', contact_number='0000000')


def _create_patient(username='pat_test'):
    user = User.objects.create_user(
        username=username, email=f'{username}@test.com',
        password='testpass123', full_name='Patient Test'
    )
    return Patient.objects.create(
        patient=user, date_of_birth='1990-01-01',
        contact_number='111', address='123 Test St'
    )


def _create_link(dentist, patient):
    return DentistPatientLink.objects.create(dentist=dentist, patient=patient, is_active=True)


def _create_scan(link, user):
    from django.core.files.base import ContentFile
    scan = CTScan(dentist_patient_link=link, uploaded_by_user=user, description='test')
    scan.file.save('test.png', ContentFile(_make_png_bytes()), save=False)
    scan.save()
    return scan


SAMPLE_DETECTIONS = [
    {'class': 'tooth_decay', 'confidence': 0.85, 'region': 'upper_jaw', 'bbox': [10, 5, 40, 30]},
    {'class': 'wisdom_tooth', 'confidence': 0.72, 'region': 'lower_jaw', 'bbox': [50, 40, 80, 60]},
]

SAMPLE_REPORT_TEXT = (
    "PANORAMIC RADIOGRAPH — AI-ASSISTED ANALYSIS REPORT\n"
    "Patient: Patient Test\n"
    "3. SUMMARY\nTwo findings detected.\n"
    "⚠ AI-GENERATED REPORT — PENDING CLINICIAN VALIDATION\n"
)


# ─── Base class: suppresses signal dispatch so tests don't need Redis ─────────

class _NoSignalBase(TestCase):
    """Patches only .delay() on the analysis task so the signal never hits the
    broker, while leaving the task callable directly for tests that need it."""
    def setUp(self):
        patcher = patch.object(_analysis_task, 'delay')
        patcher.start()
        self.addCleanup(patcher.stop)


# ─── Task-level tests ─────────────────────────────────────────────────────────

class TaskQueuedOnScanCreationTest(TestCase):
    @patch('dentapp.tasks.analysis.analyze_ct_scan_and_generate_report')
    def test_task_queued_when_scan_created(self, mock_task):
        dentist = _create_dentist('dr_signal')
        patient = _create_patient('pat_signal')
        link = _create_link(dentist, patient)
        _create_scan(link, dentist.dentist)
        mock_task.delay.assert_called_once()

    @patch('dentapp.tasks.analysis.analyze_ct_scan_and_generate_report')
    def test_task_not_queued_on_update(self, mock_task):
        dentist = _create_dentist('dr_update')
        patient = _create_patient('pat_update')
        link = _create_link(dentist, patient)
        scan = _create_scan(link, dentist.dentist)
        mock_task.delay.reset_mock()
        scan.description = 'updated'
        scan.save(update_fields=['description'])
        mock_task.delay.assert_not_called()


class ReportAutoGeneratedTest(_NoSignalBase):
    @patch('dentapp.tasks.analysis.ReportGenerationService.generate_report', return_value=SAMPLE_REPORT_TEXT)
    @patch('dentapp.tasks.analysis.YOLOInferenceService.infer_and_overlay', return_value=(SAMPLE_DETECTIONS, _make_png_bytes()))
    def test_report_created_with_auto_generated_status(self, mock_infer_overlay, mock_report):
        from dentapp.tasks.analysis import analyze_ct_scan_and_generate_report
        dentist = _create_dentist('dr_report')
        patient = _create_patient('pat_report')
        link = _create_link(dentist, patient)
        scan = _create_scan(link, dentist.dentist)

        analyze_ct_scan_and_generate_report(scan.pk)

        report = DentalReport.objects.get(ct_scan=scan)
        self.assertEqual(report.status, 'auto_generated')
        self.assertEqual(report.report_text, SAMPLE_REPORT_TEXT)
        self.assertEqual(report.raw_detections, SAMPLE_DETECTIONS)
        self.assertEqual(report.edit_count, 0)
        self.assertIsNone(report.deleted_at)

    @patch('dentapp.tasks.analysis.ReportGenerationService.generate_report', return_value=SAMPLE_REPORT_TEXT)
    @patch('dentapp.tasks.analysis.YOLOInferenceService.infer_and_overlay', return_value=(SAMPLE_DETECTIONS, _make_png_bytes()))
    def test_annotated_scan_created(self, mock_infer_overlay, mock_report):
        from dentapp.tasks.analysis import analyze_ct_scan_and_generate_report
        dentist = _create_dentist('dr_overlay')
        patient = _create_patient('pat_overlay')
        link = _create_link(dentist, patient)
        scan = _create_scan(link, dentist.dentist)

        analyze_ct_scan_and_generate_report(scan.pk)

        self.assertEqual(AnnotatedScan.objects.filter(ct_scan=scan).count(), 1)


# ─── Dentist edit / confirm / delete tests ───────────────────────────────────

class DentalReportEditTest(_NoSignalBase):
    def setUp(self):
        super().setUp()
        self.dentist = _create_dentist('dr_edit')
        self.patient = _create_patient('pat_edit')
        self.link = _create_link(self.dentist, self.patient)
        self.scan = _create_scan(self.link, self.dentist.dentist)
        self.report = DentalReport.objects.create(
            ct_scan=self.scan,
            patient=self.patient,
            dentist=self.dentist,
            raw_detections=SAMPLE_DETECTIONS,
            report_text='Original text.',
            status='auto_generated',
        )
        self.client = APIClient()
        self.client.force_authenticate(user=self.dentist.dentist)

    def test_dentist_can_edit_report_text(self):
        resp = self.client.patch(
            f'/dental-reports/{self.report.pk}/edit/',
            {'report_text': 'Edited text.'},
            format='json',
        )
        self.assertEqual(resp.status_code, 200)
        self.report.refresh_from_db()
        self.assertEqual(self.report.report_text, 'Edited text.')
        self.assertEqual(self.report.status, 'edited')
        self.assertEqual(self.report.edit_count, 1)

    def test_edit_count_increments(self):
        for i in range(3):
            self.client.patch(
                f'/dental-reports/{self.report.pk}/edit/',
                {'report_text': f'Edit {i}'},
                format='json',
            )
        self.report.refresh_from_db()
        self.assertEqual(self.report.edit_count, 3)


class DentalReportConfirmImmutableTest(_NoSignalBase):
    def setUp(self):
        super().setUp()
        self.dentist = _create_dentist('dr_confirm')
        self.patient = _create_patient('pat_confirm')
        self.link = _create_link(self.dentist, self.patient)
        self.scan = _create_scan(self.link, self.dentist.dentist)
        self.report = DentalReport.objects.create(
            ct_scan=self.scan, patient=self.patient, dentist=self.dentist,
            raw_detections=[], report_text='Final text.', status='edited',
        )
        self.client = APIClient()
        self.client.force_authenticate(user=self.dentist.dentist)

    def test_confirm_sets_status(self):
        resp = self.client.post(f'/dental-reports/{self.report.pk}/confirm/')
        self.assertEqual(resp.status_code, 200)
        self.report.refresh_from_db()
        self.assertEqual(self.report.status, 'confirmed')

    def test_patch_after_confirm_returns_403(self):
        self.report.status = 'confirmed'
        self.report.save(update_fields=['status'])
        resp = self.client.patch(
            f'/dental-reports/{self.report.pk}/edit/',
            {'report_text': 'Should be blocked.'},
            format='json',
        )
        self.assertEqual(resp.status_code, 403)
        self.report.refresh_from_db()
        self.assertEqual(self.report.report_text, 'Final text.')

    def test_raw_detections_never_change(self):
        original = list(self.report.raw_detections)
        self.client.patch(
            f'/dental-reports/{self.report.pk}/edit/',
            {'raw_detections': [{'class': 'injected'}], 'report_text': 'ok'},
            format='json',
        )
        self.report.refresh_from_db()
        self.assertEqual(self.report.raw_detections, original)


class SoftDeleteAuditTrailTest(_NoSignalBase):
    def setUp(self):
        super().setUp()
        self.dentist = _create_dentist('dr_del')
        self.patient = _create_patient('pat_del')
        self.link = _create_link(self.dentist, self.patient)
        self.scan = _create_scan(self.link, self.dentist.dentist)
        self.report = DentalReport.objects.create(
            ct_scan=self.scan, patient=self.patient, dentist=self.dentist,
            raw_detections=[], report_text='To be deleted.', status='auto_generated',
        )
        self.client = APIClient()
        self.client.force_authenticate(user=self.dentist.dentist)

    def test_delete_sets_deleted_at(self):
        resp = self.client.delete(f'/dental-reports/{self.report.pk}/delete/')
        self.assertEqual(resp.status_code, 204)
        self.report.refresh_from_db()
        self.assertIsNotNone(self.report.deleted_at)
        self.assertEqual(self.report.status, 'deleted')

    def test_deleted_report_still_in_db(self):
        self.client.delete(f'/dental-reports/{self.report.pk}/delete/')
        self.assertTrue(DentalReport.objects.filter(pk=self.report.pk).exists())

    def test_deleted_report_excluded_from_list(self):
        self.report.deleted_at = timezone.now()
        self.report.status = 'deleted'
        self.report.save()
        resp = self.client.get('/dental-reports/')
        ids = [r['id'] for r in resp.data]
        self.assertNotIn(self.report.pk, ids)


# ─── Error-handling tests ─────────────────────────────────────────────────────

class YOLOFailureTest(_NoSignalBase):
    @patch('dentapp.tasks.analysis.YOLOInferenceService.infer_and_overlay', side_effect=RuntimeError('GPU OOM'))
    def test_yolo_failure_creates_error_report(self, mock_infer_overlay):
        dentist = _create_dentist('dr_yolo_fail')
        patient = _create_patient('pat_yolo_fail')
        link = _create_link(dentist, patient)
        scan = _create_scan(link, dentist.dentist)

        # max_retries=0 makes the retry branch always False → falls through to error report
        with patch.object(_analysis_task, 'max_retries', 0):
            _analysis_task(scan.pk)

        report = DentalReport.objects.get(ct_scan=scan, status='error')
        self.assertIn('inference', report.error_message.lower())


class OpenRouterFailureTest(_NoSignalBase):
    @patch(
        'dentapp.tasks.analysis.ReportGenerationService.generate_report',
        side_effect=RuntimeError('OpenRouter HTTP 429'),
    )
    @patch('dentapp.tasks.analysis.YOLOInferenceService.infer_and_overlay', return_value=(SAMPLE_DETECTIONS, _make_png_bytes()))
    def test_openrouter_failure_creates_error_report(self, mock_infer_overlay, mock_report):
        dentist = _create_dentist('dr_api_fail')
        patient = _create_patient('pat_api_fail')
        link = _create_link(dentist, patient)
        scan = _create_scan(link, dentist.dentist)

        with patch.object(_analysis_task, 'max_retries', 0):
            _analysis_task(scan.pk)

        report = DentalReport.objects.get(ct_scan=scan, status='error')
        self.assertIn('generation', report.error_message.lower())


# ─── Permission tests ─────────────────────────────────────────────────────────

class DentistPermissionTest(_NoSignalBase):
    def setUp(self):
        super().setUp()
        self.dentist_a = _create_dentist('dr_a')
        self.dentist_b = _create_dentist('dr_b')
        self.patient = _create_patient('pat_perm')
        self.link = _create_link(self.dentist_a, self.patient)
        self.scan = _create_scan(self.link, self.dentist_a.dentist)
        self.report = DentalReport.objects.create(
            ct_scan=self.scan, patient=self.patient, dentist=self.dentist_a,
            raw_detections=[], report_text='Private.', status='auto_generated',
        )

    def test_dentist_sees_only_own_patients(self):
        client = APIClient()
        client.force_authenticate(user=self.dentist_b.dentist)
        resp = client.get('/dental-reports/')
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(len(resp.data), 0)

    def test_owning_dentist_can_see_report(self):
        client = APIClient()
        client.force_authenticate(user=self.dentist_a.dentist)
        resp = client.get('/dental-reports/')
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(len(resp.data), 1)

    def test_other_dentist_cannot_edit(self):
        client = APIClient()
        client.force_authenticate(user=self.dentist_b.dentist)
        resp = client.patch(
            f'/dental-reports/{self.report.pk}/edit/',
            {'report_text': 'Stolen edit.'},
            format='json',
        )
        self.assertEqual(resp.status_code, 404)

    def test_unauthenticated_blocked(self):
        client = APIClient()
        resp = client.get('/dental-reports/')
        self.assertEqual(resp.status_code, 401)
